services:
  - type: web
    name: medical-lab-backend
    env: python
    region: oregon
    pythonVersion: 3.12.13
    buildCommand: poetry install --no-root
    startCommand: "uvicorn main_backend:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql://labdb_gq1x_user:XtErz71QMvZsv07LEj9PrL0hcNM9hkK6@dpg-d26b2d63jp1c73cseb50-a/labdb_gq1x
      - key: SECRET_KEY
        value: your_default_secret_key
      - key: EMAIL_USER
        value: medicallabresults@gmail.com
      - key: EMAIL_PASSWORD
        value: MedicalLab%40results1
