services:
  - type: web
    name: medical-lab-backend
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medical-lab-db
          property: connectionString
      - key: SECRET_KEY
        value: your_default_secret_key
