services:
  - type: web
    name: medical-lab-backend
    env: python
    region: oregon
    pythonVersion: 3.12.13
    buildCommand: poetry install --no-root
    startCommand: "uvicorn main_backend:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Mac@supabase1@db.omcidfuqjfciohudjujd.supabase.co:5432/postgres
      - key: SECRET_KEY
        value: your_default_secret_key
      # Add other environment variables here as needed
