"""Add contact_email to Laboratory

Revision ID: 36c8d561bb98
Revises: 
Create Date: 2025-07-15 17:22:13.861581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c8d561bb98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratories', sa.Column('contact_email', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=1)
    op.drop_column('laboratories', 'contact_email')
    # ### end Alembic commands ###
